DISTMONGO-216 Release notes 4.4.19
percona/distmongo-docs pull request #132
Opened 2023-03-15 11:12 UTC by nastena1606

modified:   .github/workflows/main.yml
	modified:   docs/css/percona.css
	modified:   docs/index.md
	modified:   docs/release-notes-v4.4.18.md
	new file:   docs/release-notes-v4.4.19.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml
	new file:   variables.yml

2023-03-15 11:36 UTC, olexandr-havryliak approved these changes

2023-03-15 12:38 UTC, sandraromanchenko requested changes

2023-03-15 12:38 UTC, sandraromanchenko commented on docs/release-notes-v4.4.19.md
> +| **Release date** | December 19, 2022 |
```suggestion
| **Release date** | March 20, 2023 |
```

2023-03-15 12:38 UTC, sandraromanchenko commented on docs/release-notes-v4.4.19.md
> +This release of Percona Distribution for MongoDB is based on [Percona Server for MongoDB 4.4.19-19](https://docs.percona.com/percona-server-for-mongodb/4.4/release_notes/4.4.19-19.html) and [Percona
```suggestion
This release of Percona Distribution for MongoDB is based on [Percona Server for MongoDB 4.4.19-19](https://docs.percona.com/percona-server-for-mongodb/4.4/release_notes/4.4.19-19.html) and [Percona Backup for MongoDB 2.0.4](https://docs.percona.com/percona-backup-mongodb/release-notes/2.0.4.html).
```

2023-03-15 12:38 UTC, sandraromanchenko commented on docs/release-notes-v4.4.19.md
> +The bug fixes and improvements provided by MongoDB and included in Percona Server for MongoDB 5.0.15-13 are the following:
```suggestion
The bug fixes and improvements provided by MongoDB and included in Percona Server for MongoDB 4.4.19-19 are the following:
```

2023-03-16 07:30 UTC, sandraromanchenko approved these changes

2023-03-17 14:28 UTC, janwieremjewicz approved these changes

2023-03-20 13:27 UTC, merged