DISTMONGO-221 Release notes 6.0.5
percona/distmongo-docs pull request #139
Opened 2023-03-28 13:05 UTC by nastena1606

modified:   .github/workflows/main.yml
	modified:   docs/css/percona.css
	modified:   docs/index.md
	new file:   docs/release-notes-v6.0.5.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml
	new file:   variables.yml

2023-03-28 13:14 UTC, sandraromanchenko requested changes

2023-03-28 13:14 UTC, sandraromanchenko commented on docs/release-notes-v6.0.5.md
> +# Percona Distribution for MongoDB 6.0.5 (2023-01-30)
```suggestion
# Percona Distribution for MongoDB 6.0.5 (2023-03-29)
```

2023-03-28 13:14 UTC, sandraromanchenko commented on docs/release-notes-v6.0.5.md
> +MongoDB efficiently with the data being consistently backed up.
pls remove extra 'enter')

2023-03-28 13:21 UTC, sandraromanchenko approved these changes

2023-03-29 07:21 UTC, olexandr-havryliak approved these changes

2023-03-29 14:56 UTC, merged