DISTMONGO-229 Release notes 6.0.6
percona/distmongo-docs pull request #157
Opened 2023-05-15 08:32 UTC by nastena1606

modified:   .github/workflows/main.yml
	new file:   docs/release-notes-v6.0.6.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-05-23 16:19 UTC, sandraromanchenko requested changes

2023-05-23 16:19 UTC, sandraromanchenko commented on docs/release-notes-v6.0.6.md
> +| Release date:     | May 18, 2023      |
```suggestion
| Release date:     | May 25, 2023      |
```

2023-05-23 16:19 UTC, sandraromanchenko commented on variables.yml
> +release_date: 2023-05-18
```suggestion
release_date: 2023-05-25
```

2023-05-23 16:19 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle: 6.0.6 (May 18, 2023)
```suggestion
          cover_subtitle: 6.0.6 (May 25, 2023)
```

2023-05-24 09:46 UTC, sandraromanchenko approved these changes

2023-05-24 10:04 UTC, olexandr-havryliak approved these changes

2023-05-25 13:36 UTC, merged