DISTMONGO-283 Release notes 6.0.14
percona/distmongo-docs pull request #218
Opened 2024-03-21 08:56 UTC by nastena1606

new file:   docs/release-notes-v6.0.14.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-03-22 13:18 UTC, sandraromanchenko requested changes

2024-03-22 13:18 UTC, sandraromanchenko commented on mkdocs-base.yml
> +          cover_subtitle: 6.0.14 (March 24, 2024)
```suggestion
          cover_subtitle: 6.0.14 (March 26, 2024)
```

2024-03-22 14:07 UTC, sandraromanchenko approved these changes

2024-03-26 09:34 UTC, janwieremjewicz approved these changes
LGTM

2024-03-26 15:14 UTC, merged