DISTMONGO-315 Release notes 7.0.14
percona/distmongo-docs pull request #261
Opened 2024-09-03 09:38 UTC by nastena1606

new file:   docs/release-notes-v7.0.14.md
	modified:   docs/release-notes.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-09-05 09:48 UTC, nastena1606 commented on docs/release-notes-v7.0.14.md
> +The enhanced telemetry feature provides comprehensive information about how it works, its components and metrics as well as updated methods how to disable telemetry. Read more in [Telemetry on Percon
```suggestion

```

2024-09-11 10:35 UTC, sandraromanchenko requested changes

2024-09-11 10:35 UTC, sandraromanchenko commented on docs/release-notes-v7.0.14.md
> +The enhanced telemetry feature provides comprehensive information about how it works, its components and metrics as well as updated methods how to disable telemetry. Read more in [Telemetry on Percon
```suggestion
```

2024-09-11 10:42 UTC, sandraromanchenko approved these changes

2024-09-23 11:49 UTC, merged