DISTMONGO-155 Release notes 5.0.9
percona/distmongo-docs pull request #77
Opened 2022-06-13 08:37 UTC by nastena1606

modified:   source/conf.py
	modified:   source/release-notes.rst
new file: source/release-notes-v5.0.9.rst

2022-06-13 09:01 UTC, spron-in requested changes

2022-06-13 09:01 UTC, spron-in commented on source/release-notes-v5.0.9.rst
> +* the ability to use encrypted client keys/certificates through the password setting
same comment as in the server release notes - need value explanation.

2022-06-14 05:29 UTC, olexandr-havryliak approved these changes

2022-06-20 14:54 UTC, nastena1606 commented on source/release-notes-v5.0.9.rst
> +* the ability to use encrypted client keys/certificates through the password setting
Amended

2022-06-20 14:54 UTC, merged